blog/urls.py
from django.conf.urls import url

from .views import (
    PostCreate, PostDelete, PostList, PostUpdate,
    post_detail)

urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail,
        name='blog_post_detail'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
]

organizer/urls.py
from django.conf.urls import url

from .views import (
    NewsLinkCreate, NewsLinkDelete,
    NewsLinkUpdate, StartupCreate, StartupDelete,
    StartupUpdate, TagCreate, TagDelete,
    TagUpdate, startup_detail, startup_list,
    tag_detail, tag_list)

urlpatterns = [
    url(r'^newslink/create/$',
        NewsLinkCreate.as_view(),
        name='organizer_newslink_create'),
    url(r'^newslink/delete/(?P<pk>\d+)/$',
        NewsLinkDelete.as_view(),
        name='organizer_newslink_delete'),
    url(r'^newslink/update/(?P<pk>\d+)/$',
        NewsLinkUpdate.as_view(),
        name='organizer_newslink_update'),
    url(r'^startup/$',
        startup_list,
        name='organizer_startup_list'),
    url(r'^startup/create/$',
        StartupCreate.as_view(),
        name='organizer_startup_create'),
    url(r'^startup/(?P<slug>[\w\-]+)/$',
        startup_detail,
        name='organizer_startup_detail'),
    url(r'^startup/(?P<slug>[\w\-]+)/delete/$',
        StartupDelete.as_view(),
        name='organizer_startup_delete'),
    url(r'^startup/(?P<slug>[\w\-]+)/update/$',
        StartupUpdate.as_view(),
        name='organizer_startup_update'),
    url(r'^tag/$',
        tag_list,
        name='organizer_tag_list'),
    url(r'^tag/create/$',
        TagCreate.as_view(),
        name='organizer_tag_create'),
    url(r'^tag/(?P<slug>[\w\-]+)/$',
        tag_detail,
        name='organizer_tag_detail'),
    url(r'^tag/(?P<slug>[\w-]+)/delete/$',
        TagDelete.as_view(),
        name='organizer_tag_delete'),
    url(r'^tag/(?P<slug>[\w\-]+)/update/$',
        TagUpdate.as_view(),
        name='organizer_tag_update'),
]

suorganizer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from blog import urls as blog_urls
from organizer import urls as organizer_urls

from .views import redirect_root

urlpatterns = [
    url(r'^$', redirect_root),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include(blog_urls)),
    url(r'^', include(organizer_urls)),
]

organizer/models.py
from django.core.urlresolvers import reverse
from django.db import models


# Model Field Reference
# https://docs.djangoproject.com/en/1.8/ref/models/fields/


class Tag(models.Model):
    name = models.CharField(
        max_length=31, unique=True)
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config.')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name.title()

    def get_absolute_url(self):
        return reverse('organizer_tag_detail',
                       kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizer_tag_delete',
                       kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizer_tag_update',
                       kwargs={'slug': self.slug})


class Startup(models.Model):
    name = models.CharField(
        max_length=31, db_index=True)
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config.')
    description = models.TextField()
    founded_date = models.DateField(
        'date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('organizer_startup_detail',
                       kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizer_startup_delete',
                       kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizer_startup_update',
                       kwargs={'slug': self.slug})


class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup)

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'

    def __str__(self):
        return "{}: {}".format(
            self.startup, self.title)

    def get_absolute_url(self):
        return self.startup.get_absolute_url()

    def get_delete_url(self):
        return reverse(
            'organizer_newslink_delete',
            kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse(
            'organizer_newslink_update',
            kwargs={'pk': self.pk})

organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import NewsLink, Startup, Tag


class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'


class SlugCleanMixin:
    """Mixin class for slug cleaning method."""

    def clean_slug(self):
        new_slug = (
            self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError(
                'Slug may not be "create".')
        return new_slug


class StartupForm(
        SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = '__all__'


class TagForm(
        SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()

organizer/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import (
    get_object_or_404, redirect, render)
from django.views.generic import View

from .forms import (
    NewsLinkForm, StartupForm, TagForm)
from .models import NewsLink, Startup, Tag
from .utils import (
    ObjectCreateMixin, ObjectDeleteMixin,
    ObjectUpdateMixin)


class NewsLinkCreate(ObjectCreateMixin, View):
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form.html'


class NewsLinkDelete(View):

    def get(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk)
        return render(
            request,
            'organizer/'
            'newslink_confirm_delete.html',
            {'newslink': newslink})

    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk)
        startup = newslink.startup
        newslink.delete()
        return redirect(startup)


class NewsLinkUpdate(View):
    form_class = NewsLinkForm
    template_name = (
        'organizer/newslink_form_update.html')

    def get(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk)
        context = {
            'form': self.form_class(
                instance=newslink),
            'newslink': newslink,
        }
        return render(
            request, self.template_name, context)

    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk)
        bound_form = self.form_class(
            request.POST, instance=newslink)
        if bound_form.is_valid():
            new_newslink = bound_form.save()
            return redirect(new_newslink)
        else:
            context = {
                'form': bound_form,
                'newslink': newslink,
            }
            return render(
                request,
                self.template_name,
                context)


class StartupCreate(ObjectCreateMixin, View):
    form_class = StartupForm
    template_name = 'organizer/startup_form.html'


class StartupDelete(ObjectDeleteMixin, View):
    model = Startup
    success_url = reverse_lazy(
        'organizer_startup_list')
    template_name = (
        'organizer/startup_confirm_delete.html')


def startup_detail(request, slug):
    startup = get_object_or_404(
        Startup, slug__iexact=slug)
    return render(
        request,
        'organizer/startup_detail.html',
        {'startup': startup})


def startup_list(request):
    return render(
        request,
        'organizer/startup_list.html',
        {'startup_list': Startup.objects.all()})


class StartupUpdate(ObjectUpdateMixin, View):
    form_class = StartupForm
    model = Startup
    template_name = (
        'organizer/startup_form_update.html')


class TagCreate(ObjectCreateMixin, View):
    form_class = TagForm
    template_name = 'organizer/tag_form.html'


class TagDelete(ObjectDeleteMixin, View):
    model = Tag
    success_url = reverse_lazy(
        'organizer_tag_list')
    template_name = (
        'organizer/tag_confirm_delete.html')


def tag_detail(request, slug):
    tag = get_object_or_404(
        Tag, slug__iexact=slug)
    return render(
        request,
        'organizer/tag_detail.html',
        {'tag': tag})


def tag_list(request):
    return render(
        request,
        'organizer/tag_list.html',
        {'tag_list': Tag.objects.all()})


class TagUpdate(ObjectUpdateMixin, View):
    form_class = TagForm
    model = Tag
    template_name = (
        'organizer/tag_form_update.html')

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/newslink_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete News Article
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ newslink.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete link to
          article {{ newslink.name }}?
        </p>
        <a href="{{ newslink.get_absolute_url }}">
          Cancel</a>
        <button type="submit">
          Delete Article Link</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Link News Article to Startup
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_newslink_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Link Article</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/newslink_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update News Article
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ newslink.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Update Article Link</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/startup_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Startup
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ startup.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          startup {{ startup.name }}?
        </p>
        <a href="{{ startup.get_absolute_url }}">
          Cancel</a>
        <button type="submit">Delete Startup</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ startup.name }}
{% endblock %}

{% block content %}
<article>

  <h2>{{ startup.name }}</h2>
    <ul>
        <li>
          <a href="{{ startup.get_update_url }}">
            Edit Startup</a></li>
        <li>
                <a href="{{ startup.get_delete_url }}">
                  Delete Startup</a></li>
    </ul>
  <dl>
    <dt>Date Founded</dt>
      <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
      <dd>{{ startup.website|urlize }}</dd>
    <dt>Contact</dt>
      <dd>{{ startup.contact }}</dd>

      <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}

  </dl>

  {{ startup.description|linebreaks }}

      {% if startup.newslink_set.all %}
          <section>
            <h3>Recent News</h3>
              <p>
                <a href="{% url 'organizer_newslink_create' %}">
                  Add Article</a></p>
            <ul>
              {% for newslink in startup.newslink_set.all %}
                <li>
                  <a href="{{ newslink.link }}">
                    {{ newslink.title|title }}</a>
                    <ul>
                        <li>
                          <a href="{{ newslink.get_update_url }}">
                            Edit Link</a></li>
                        <li>
                          <a href="{{ newslink.get_delete_url }}">
                            Delete Link</a></li>
                    </ul>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

      {% if startup.blog_posts.all %}
          <section>
            <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
            <ul>
              {% for post in startup.blog_posts.all %}
                <li>
                  <a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}</a>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

</article>
{% endblock %}

organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_startup_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Create Startup</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Startup
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ startup.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Update Startup</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block content %}
  <h2>Startup List</h2>
    <div>
      <a href="{% url 'organizer_startup_create' %}">
        Create New Startup</a>
    </div>
  <ul>
    {% for startup in startup_list %}
      <li>
        <a href="{{ startup.get_absolute_url }}">
          {{ startup.name }}</a>
          <ul>
              <li>
                <a href="{{ startup.get_update_url }}">
                  Edit Startup</a></li>
             <li>
                <a href="{{ startup.get_delete_url }}">
                  Delete Startup</a></li>
          </ul>
      </li>
    {% empty %}
      <li><em>No Startups Available</em></li>
    {% endfor %}
  </ul>
{% endblock %}

organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ tag.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          tag {{ tag.name }}?
        </p>
        <a href="{{ tag.get_absolute_url }}">
          Cancel</a>
        <button type="submit">Delete Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
  <h2>{{ tag.name|title }}</h2>
    <ul>
        <li>
          <a href="{{ tag.get_update_url }}">
            Edit Tag</a></li>
        <li>
          <a href="{{ tag.get_delete_url }}">
            Delete Tag</a></li>
    </ul>
  {% if tag.startup_set.all %}
    <section>
      <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
      <p>
        Tag is associated with
        {{ tag.startup_set.count }}
        startup{{ tag.startup_set.count|pluralize }}.
      </p>
      <ul>
        {% for startup in tag.startup_set.all %}
          <li><a href="{{ startup.get_absolute_url }}">
            {{ startup.name }}
          </a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
      {% if tag.blog_posts.all %}
        <section>
          <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
          <ul>
            {% for post in tag.blog_posts.all %}
              <li><a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
              </a></li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
      {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
      {% endif %}
{% endblock %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_tag_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Create Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Tag
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ tag.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Update Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block content %}
  <h2>Tag List</h2>
    <div>
      <a href="{% url 'organizer_tag_create' %}">
        Create New Tag</a>
    </div>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_absolute_url }}">
          {{ tag.name|title }}</a>
          <ul>
            <li>
              <a href="{{ tag.get_update_url }}">
                Edit Tag</a></li>
            <li>
              <a href="{{ tag.get_delete_url }}">
                Delete Tag</a></li>
          </ul>
      </li>
    {% empty %}
      <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}